### ISSUE TITLE
你好，请教下，invoker能不能提供同步方法

### ISSUE THREAD

**Issue by hsuehic** [Corey600/zoodubbo#1]
我想用zoobubbo来调用服务 通过 handlerbars渲染前端页面html.

希望可以提供些意见或建议。
非常感谢。

**Comment by Corey600** [comment]
@hsuehic 不能也不应该同步的。
dubbo本身就是服务之间的调用，由于node是单线程运行的，你一旦同步就会卡死整个服务。
想用handlerbars也是分前端渲染和服务器渲染的。前端渲染你直接阅读[官方文档](http://handlebarsjs.com/)吧。
后端渲染的话看你用什么框架，然后选择相应的中间件模块。比如你如果使用koa，可以看看这个[koa-hbs](https://github.com/gilt/koa-hbs)。

**Comment by hsuehic** [comment]
前端我用的express-handlebars ,我再想想办法，谢谢了。
